name: Generate ASCII Artwork

on:
    push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Install Cowsay prog
              run: sudo apt-get install cowsay

            - name: Execute cowsay cmd
              run:  cowsay -f dragon "Run for cover, I am A Dragon....RAWR" >> dragon.txt

            - name: Sleep 30 s
              run: sleep 30

    build_job_2:
        runs-on: ubuntu-latest
        steps:
            - name: Sleep 10 s
              run: sleep 10

            - name: Test file exists
              uses: grep -i "dragon" dragon.txt

    build_job_3:
        runs-on: ubuntu-latest
        steps:
            - name: Read file
              uses: grep -i "dragon" dragon.txt

            - name: Deploy
              uses: Echo Deploy